name: dartmon_cli
description: A command line tool to perform hot reload on dart and other applications
version: 1.0.0
repository: https://github.com/ShivanshuKGupta/dartmon

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  # path: ^1.8.0

executables:
  dartmon: dartmon

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
