name: dartmon
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.2

dependencies:
  # path: ^1.8.0

executables:
  dartmon: dartmon

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
